version: '3'

services:
  php:
    build: ./docker/php/
    volumes:
      - .:/usr/src/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      # You can change this env to allow profiling or debugging your application with Xdebug.
      # This is disabled by default because it adds plenty of overhead when it's not needed.
      # Default: debug
      - XDEBUG_MODE=debug
      - XDEBUG_IDE_KEY=DEBUG
      # Directory to store Xdebug profiling data
      - XDEBUG_OUTPUT_DIR=/tmp/xdebug
      # Use OSX IP address loopback hack: https://gist.githubusercontent.com/ralphschindler/535dc5916ccbd06f53c1b0ee5a868c93/raw/com.ralphschindler.docker_10254_alias.plist
      # This can be overridden by you
      - XDEBUG_CLIENT_HOST=10.254.254.254
      # This is the default recommended port.
      - XDEBUG_CLIENT_PORT=9003
      # Log to container's STDOUT.
      - XDEBUG_LOG=/proc/self/fd/1
      # https://xdebug.org/docs/all_settings#start_with_request
      - XDEBUG_START_WITH_REQUEST=yes
      # https://xdebug.org/docs/all_settings#discover_client_host
      - XDEBUG_DISCOVER_CLIENT_HOST=1